[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from = ":slug"
  to = "/posts/:slug"
  status = 301
